name: Kind Cluster

on:
  push:
    branches:
      - main

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

  install-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Create and start Docker Compose services
        run: |
          echo "version: '3'
services:
  install-docker:
    image: docker:latest
    privileged: true
    command: /bin/sh -c \"curl -fsSL https://get.docker.com | sh\"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - docker-wait

  docker-wait:
    image: alpine
    command: /bin/sh -c \"while ! nc -z localhost 2375; do sleep 1; done\"
    depends_on:
      - install-docker

  sample-container:
    image: nginx:latest
    depends_on:
      - install-docker
    ports:
      - \"8080:80\"" > docker-compose.yml

      - name: Start Docker Compose
        run: docker-compose up -d
