name: install kubectl

on: 
  push:
    
jobs:
   build_and_test:
    runs-on: ubuntu-latest
    steps:
       - name: 'Upload Artifact'
         uses: actions/upload-artifact@v4
         with:
            name: my-artifact
            path: /home/runner/work/.github/workflows/install-kubectl.sh
            retention-days: 5

    
       - name: run a shell script
         run: |
           sudo apt-get update
           #!/bin/bash
           ls
           pwd
           sudo chmod +x /home/runner/work/.github/workflows./install-kubectl.sh
           ./install-kubectl.sh
           pwd
           ls -a
           kubectl version --client
