name: Kind Clustera
on:
  push:
    branches:
    - main

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common
        sudo sh -c "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
        sudo apt update
        apt-cache policy docker-ce
        sudo apt install docker-ce
        sudo systemctl status docker

    - name: Install kubectl
      run: 
        sudo apt-get update
        sudo docker --version
        sudo sh -c "curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl""
        sudo sh -c "curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256""
        sudo sh -c "echo "$(sudo cat kubectl.sha256)  kubectl" | sha256sum --check" 
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client
        

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1
