name: kubectl installation

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
         - name: Install kubectl
           run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/
            kubectl version --client





            

    
