name: install kubectl

on: 
  push:
    
jobs:
   build_and_test:
    runs-on: ubuntu-latest
    steps:

       - name: Checkout code
         uses: actions/checkout@v2
    
       - name: Upload artifact
         uses: actions/upload-artifact@v2
         with: 
              name: my-artifact
              path: install-kubectl.sh
    
            
       - name: run a shell script
         run: |
           sudo apt-get update
           #!/bin/bash
           ls
           pwd
           sudo chmod +x /home/runner/work/.github/workflows./install-kubectl.sh
           ./install-kubectl.sh
           pwd
           ls -a
           kubectl version --client
